# ==============================================================================
#           MONUMENT MANIFEST (v1.0 - Sovereign Core Standard)
# ==============================================================================
# Code Forge - Autonomous code generation and development monument

kind: Monument
version: "1.0"
name: "code_forge"
summary: "Autonomous code generation, review, and deployment monument"
author: "PRAETORIAN_CHIMERA"
state: "unstable"

description: |
  Code Forge is a complete autonomous development monument that:
  - Generates code based on specifications
  - Reviews and refactors existing code
  - Runs tests and quality checks
  - Manages version control
  - Deploys to various targets
  
  This monument demonstrates advanced AI-assisted development workflows.

# --- INFRASTRUCTURE STACK (Relics) ---
infrastructure:
  relics:
    - name: "code_repository"
      type: "storage"
      path: "../../relics/kv_store/relic.yml"
      required: true
      config:
        purpose: "Store code artifacts, versions, and metadata"
    
    - name: "build_cache"
      type: "cache"
      path: "../../relics/kv_store/relic.yml"
      required: true
      config:
        purpose: "Cache build artifacts and dependencies"

# --- INTELLIGENCE LAYER (Agents) ---
intelligence:
  agents:
    - name: "code_architect"
      role: "orchestrator"
      path: "../../agents/research_orchestrator/agent.yml"
      auto_start: true
      config:
        task: "Design code architecture and coordinate development"
        specialization: "software_architecture"
    
    - name: "code_reviewer"
      role: "worker"
      path: "../../agents/research_orchestrator/agents/web_researcher/agent.yml"
      auto_start: false
      config:
        task: "Review code quality and suggest improvements"
        specialization: "code_review"

# --- AUTOMATION LAYER (Workflows) ---
automation:
  workflows:
    - name: "code_generation_pipeline"
      trigger: "on_demand"
      path: "../../workflow/simple_data_processing.workflow.yml"
      config:
        description: "Generate code from specifications"
    
    - name: "test_and_deploy"
      trigger: "on_demand"
      config:
        description: "Run tests and deploy code"
    
    - name: "code_review_workflow"
      trigger: "scheduled"
      schedule: "0 */2 * * *"  # Every 2 hours
      config:
        description: "Automated code review cycle"

# --- TOOLS INTEGRATION ---
tools:
  - name: "sys_info"
    path: "../../tools/sys_info_v2/tool.yml"
    purpose: "System diagnostics for deployment targets"

# --- DEPLOYMENT ---
deployment:
  type: "docker-compose"
  compose_file: "./docker-compose.yml"
  services:
    - code_repository
    - build_cache
  
  environment:
    FORGE_NAME: "Code Forge"
    SUPPORTED_LANGUAGES: "python,javascript,go,rust,java"
    AUTO_TEST: "true"
    AUTO_DEPLOY: "false"
    LOG_LEVEL: "INFO"

# --- MONUMENT INTERFACE ---
interface:
  type: "rest_api"
  base_url: "http://localhost:9100"
  endpoints:
    - name: "generate_code"
      method: "POST"
      path: "/code/generate"
      description: "Generate code from specification"
      
    - name: "review_code"
      method: "POST"
      path: "/code/review"
      description: "Review existing code"
      
    - name: "run_tests"
      method: "POST"
      path: "/code/test"
      description: "Run test suite"
      
    - name: "deploy_code"
      method: "POST"
      path: "/code/deploy"
      description: "Deploy code to target"
      
    - name: "get_status"
      method: "GET"
      path: "/status"
      description: "Get forge status"

# --- CONFIGURATION ---
config:
  features:
    - "code_generation"
    - "code_review"
    - "automated_testing"
    - "version_control"
    - "deployment_automation"
    - "quality_metrics"
  
  supported_languages:
    - "python"
    - "javascript"
    - "typescript"
    - "go"
    - "rust"
    - "java"
  
  limits:
    max_file_size: "10MB"
    max_project_size: "1GB"
    concurrent_builds: 5
    build_timeout_seconds: 3600
  
  quality:
    min_test_coverage: 80
    max_complexity: 10
    enforce_linting: true
    enforce_formatting: true

# --- CONTEXT FEEDS ---
context_feeds:
  - id: "build_status"
    type: "periodic"
    interval: 30
    source:
      type: "internal"
      action: "get_build_status"
  
  - id: "code_metrics"
    type: "on_demand"
    source:
      type: "internal"
      action: "calculate_metrics"

# --- OBSERVABILITY ---
observability:
  metrics:
    enabled: true
    endpoint: "/metrics"
    custom_metrics:
      - "code_generation_count"
      - "test_success_rate"
      - "deployment_count"
      - "code_quality_score"
  
  logging:
    level: "INFO"
    structured: true
  
  health_checks:
    - type: "liveness"
      path: "/health/live"
      interval_seconds: 30
      
    - type: "readiness"
      path: "/health/ready"
      interval_seconds: 10

tags:
  - "monument"
  - "code-generation"
  - "development"
  - "automation"
  - "ai-assisted"

metadata:
  complexity: "complex"
  components_count: 6
  estimated_resource_usage: "medium"
  version: "1.0.0"
  experimental_features:
    - "ai_code_generation"
    - "automated_refactoring"
