version: '3.8'

services:
  journal_kv_store_app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: relic_journal_kv_store
    restart: unless-stopped
    ports:
      - "${JOURNAL_KV_STORE_PORT:-8005}:8000"
    volumes:
      - journal_kv_store_data:/data
    env_file:
      - .env.example

volumes:
  journal_kv_store_data:
