version: '3.8'

services:
  neo4j:
    image: neo4j:5.14-community
    container_name: graphrag_neo4j_mk1
    ports:
      - "7474:7474"
      - "7687:7687"
    environment:
      NEO4J_AUTH: neo4j/your_password
      NEO4J_PLUGINS: '["apoc"]'
      NEO4J_dbms_memory_heap_initial__size: 2G
      NEO4J_dbms_memory_heap_max__size: 4G
    volumes:
      - neo4j_data:/data
      - neo4j_logs:/logs
    
  redis:
    image: redis:7-alpine
    container_name: graphrag_redis_mk1
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    command: redis-server --appendonly yes --maxmemory 1gb --maxmemory-policy allkeys-lru

  app:
    build: .
    container_name: graphrag_app_mk1
    ports:
      - "8000:8000"
      - "8001:8001"
    depends_on:
      - neo4j
      - redis
    environment:
      - NEO4J_URI=bolt://neo4j:7687
      - REDIS_URL=redis://redis:6379
    volumes:
      - ./app:/app/app
      - ./voice:/app/voice
      - ./data:/app/data
    devices:
      - /dev/snd:/dev/snd  # Audio device access

volumes:
  neo4j_data:
  neo4j_logs:
  redis_data: