# ==============================================================================
#           WORKFLOW MANIFEST (v1.0 - Sovereign Core Standard)
# ==============================================================================
# Journal entry processing workflow with local implementations

kind: Workflow
version: "1.0"
name: "journal_entry_pipeline"
summary: "Complete pipeline for processing and storing journal entries"
author: "PRAETORIAN_CHIMERA"
state: "stable"

description: |
  A workflow that processes journal entries:
  - Analyzes sentiment of the entry
  - Stores in journal KV store with metadata
  - Demonstrates sequential execution with error handling

trigger:
  type: "manual"
  event: "journal.new_entry"
  parameters:
    entry_text:
      type: "string"
      description: "Journal entry text"
      required: true
      validation:
        min_length: 10
        max_length: 10000
    user_id:
      type: "string"
      description: "User identifier"
      required: true
      validation:
        pattern: "^user_[a-z0-9]+$"
    tags:
      type: "array"
      description: "Entry tags"
      required: false

steps:
  # Step 1: Sentiment Analysis
  - name: "analyze_sentiment"
    type: "tool"
    target: "sentiment_analyzer"
    parameters:
      text: "$(trigger.entry_text)"
      return_scores: true
    retry_policy:
      max_attempts: 3
      backoff: "exponential"
    on_failure: "continue"

  # Step 2: Get system info for metadata
  - name: "get_system_info"
    type: "tool"
    target: "sys_info"
    parameters:
      operation: "get_os"
    on_failure: "continue"

  # Step 3: Enrich entry data
  - name: "build_entry"
    type: "internal"
    parameters:
      entry_data:
        text: "$(trigger.entry_text)"
        user_id: "$(trigger.user_id)"
        tags: "$(trigger.tags)"
        timestamp: "$TIMESTAMP"
        sentiment: "$(steps.analyze_sentiment.sentiment)"
        sentiment_confidence: "$(steps.analyze_sentiment.confidence)"
        system_info: "$(steps.get_system_info)"
        workflow_id: "$WORKFLOW_ID"

  # Step 4: Store in Journal Relic
  - name: "store_entry"
    type: "relic"
    target: "journal_kv_store"
    parameters:
      key: "entry:$TIMESTAMP:$(trigger.user_id)"
      value: "$(steps.build_entry.entry_data)"
    retry_policy:
      max_attempts: 5
      backoff: "exponential"
    on_failure: "abort"

configuration:
  timeout: 300
  default_retry_policy:
    max_attempts: 3
    backoff: "exponential"
  error_handling:
    on_step_failure: "continue"
  observability:
    log_level: "INFO"
    trace_enabled: true

outputs:
  entry_id:
    source: "steps.store_entry.key"
    description: "Unique identifier for the stored journal entry"
  
  sentiment:
    source: "steps.analyze_sentiment.sentiment"
    description: "Overall sentiment of the entry"
    optional: true
  
  timestamp:
    source: "$TIMESTAMP"
    description: "Entry timestamp"

import:
  tools:
    - "../tools/sentiment_analyzer/tool.yml"
    - "../tools/sys_info/tool.yml"
  relics:
    - "../agents/journaler/relics/journal_kv_store/relic.yml"

tags:
  - "workflow"
  - "journal"
  - "production"
