# ==============================================================================
#           WORKFLOW MANIFEST (v1.0 - Sovereign Core Standard)
# ==============================================================================
# Research workflow with agent coordination

kind: Workflow
version: "1.0"
name: "multi_agent_research"
summary: "Research workflow with hierarchical agent coordination"
author: "PRAETORIAN_CHIMERA"
state: "stable"

description: |
  Research workflow demonstrating agent coordination:
  - Uses research_orchestrator agent for research tasks
  - Analyzes and stores research results
  - Demonstrates hierarchical agent delegation

trigger:
  type: "manual"
  event: "research.query"
  parameters:
    query:
      type: "string"
      description: "Research query"
      required: true
    max_sources:
      type: "integer"
      description: "Maximum sources to search"
      required: false
      default: 5

steps:
  # Step 1: Delegate research to orchestrator agent
  - name: "research_task"
    type: "agent"
    target: "research_orchestrator"
    parameters:
      task: "research"
      query: "$(trigger.query)"
      max_results: "$(trigger.max_sources)"
    retry_policy:
      max_attempts: 2
      backoff: "exponential"
    on_failure: "abort"

  # Step 2: Analyze research results sentiment
  - name: "analyze_findings"
    type: "tool"
    target: "sentiment_analyzer"
    parameters:
      text: "$(steps.research_task.findings)"
      return_scores: true
    condition: "$(steps.research_task.status) == 'success'"
    on_failure: "continue"

  # Step 3: Store results in research cache
  - name: "cache_results"
    type: "relic"
    target: "research_cache"
    parameters:
      key: "research:$(trigger.query):$TIMESTAMP"
      value:
        query: "$(trigger.query)"
        findings: "$(steps.research_task.findings)"
        sentiment: "$(steps.analyze_findings.sentiment)"
        timestamp: "$TIMESTAMP"
      ttl: 3600  # Cache for 1 hour
    condition: "$(steps.research_task.status) == 'success'"
    retry_policy:
      max_attempts: 3
      backoff: "exponential"
    on_failure: "continue"

configuration:
  timeout: 600
  default_retry_policy:
    max_attempts: 2
    backoff: "exponential"
  error_handling:
    on_step_failure: "continue"
  observability:
    log_level: "INFO"
    trace_enabled: true

outputs:
  findings:
    source: "steps.research_task.findings"
    description: "Research findings"
  
  cache_key:
    source: "steps.cache_results.key"
    description: "Cached results key"
    optional: true
  
  sentiment:
    source: "steps.analyze_findings.sentiment"
    description: "Overall sentiment of findings"
    optional: true

import:
  agents:
    - "../agents/research_orchestrator/agent.yml"
  tools:
    - "../tools/sentiment_analyzer/tool.yml"
  relics:
    - "../agents/research_orchestrator/relics/research_cache/relic.yml"

tags:
  - "workflow"
  - "research"
  - "agent-coordination"
  - "production"
