# ==============================================================================
#           WORKFLOW MANIFEST (v1.0 - Sovereign Core Standard)
# ==============================================================================
# Simple workflow example with local tool implementations

kind: Workflow
version: "1.0"
name: "simple_data_processing"
summary: "Basic data processing workflow with sentiment analysis"
author: "PRAETORIAN_CHIMERA"
state: "stable"

description: |
  A simple workflow that processes text data:
  - Analyzes sentiment using local sentiment_analyzer
  - Stores results in kv_store
  Demonstrates basic workflow concepts with actual tool implementations.

trigger:
  type: "manual"
  event: "data.process"
  parameters:
    text_data:
      type: "string"
      description: "Text data to process"
      required: true
    user_id:
      type: "string"
      description: "User identifier"
      required: true

steps:
  # Step 1: Analyze sentiment
  - name: "analyze_text"
    type: "tool"
    target: "sentiment_analyzer"
    parameters:
      text: "$(trigger.text_data)"
      return_scores: true
    retry_policy:
      max_attempts: 3
      backoff: "exponential"
    on_failure: "abort"

  # Step 2: Store results
  - name: "store_results"
    type: "relic"
    target: "kv_store"
    parameters:
      key: "analysis:$(trigger.user_id):$TIMESTAMP"
      value:
        text: "$(trigger.text_data)"
        sentiment: "$(steps.analyze_text.sentiment)"
        confidence: "$(steps.analyze_text.confidence)"
        scores: "$(steps.analyze_text.scores)"
        timestamp: "$TIMESTAMP"
    condition: "$(steps.analyze_text.sentiment) != null"
    retry_policy:
      max_attempts: 5
      backoff: "exponential"
    on_failure: "abort"

configuration:
  timeout: 120
  default_retry_policy:
    max_attempts: 2
    backoff: "linear"
  error_handling:
    on_step_failure: "abort"
  observability:
    log_level: "INFO"
    trace_enabled: true

outputs:
  analysis_id:
    source: "steps.store_results.key"
    description: "Key where analysis was stored"
  
  sentiment:
    source: "steps.analyze_text.sentiment"
    description: "Detected sentiment"
  
  confidence:
    source: "steps.analyze_text.confidence"
    description: "Confidence score"

import:
  tools:
    - "../tools/sentiment_analyzer/tool.yml"
  relics:
    - "../relics/kv_store/relic.yml"

tags:
  - "workflow"
  - "data-processing"
  - "sentiment"
  - "production"
