# ==============================================================================
# PROJECT: CORTEX-PRIME - CORE SERVICES ONLY (Minimal Stack)
#
# This compose file contains only the essential services needed for basic
# operation, excluding heavy services like Neo4j. Perfect for development
# and testing the core agent loop.
# ==============================================================================

x-common-labels: &common-labels
  labels:
    project: "${PROJECT_NAME:-cortex-prime}"
    owner: "PRAETORIAN_CHIMERA"
    stack: "core"

x-common-env: &common-env
  env_file:
    - ./env/.env

services:

  # --- REDIS (Lightweight Cache) ---
  redis:
    <<: [*common-labels, *common-env]
    image: redis:7-alpine
    container_name: ${PROJECT_NAME:-cortex-prime-mk1}_redis_core
    restart: unless-stopped
    ports:
      - "${REDIS_HOST_PORT:-6380}:6379"
    volumes:
      - redis_data:/data
    command: redis-server --appendonly yes --maxmemory 512mb --maxmemory-policy allkeys-lru
    networks:
      - cortex_prime_network
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5

  # --- LLM GATEWAY (Essential for Agent Loops) ---
  llm_gateway:
    <<: [*common-labels, *common-env]
    build:
      context: ../services/llm_gateway
      dockerfile: Dockerfile
    container_name: ${PROJECT_NAME:-cortex-prime-mk1}_llm_gateway_core
    restart: unless-stopped
    ports:
      - "${LLM_GATEWAY_HOST_PORT:-8081}:8080"
    networks:
      - cortex_prime_network
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost:8080/health || exit 1"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s

  # --- CHAT TEST (Development Interface) ---
  chat_test:
    <<: [*common-labels, *common-env]
    build:
      context: ../services/chat_test
      dockerfile: Dockerfile
    container_name: ${PROJECT_NAME:-cortex-prime-mk1}_chat_test_core
    restart: unless-stopped
    depends_on:
      llm_gateway:
        condition: service_healthy
    ports:
      - "${CHAT_TEST_HOST_PORT:-8888}:8888"
    volumes:
      - ../services/chat_test:/app
    networks:
      - cortex_prime_network
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost:8888/health || exit 1"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s

  # --- WEB CLIENT (Optional UI) ---
  web_client:
    <<: [*common-labels]
    image: nginx:alpine
    container_name: ${PROJECT_NAME:-cortex-prime-mk1}_web_client_core
    restart: unless-stopped
    ports:
      - "${WEB_CLIENT_HOST_PORT:-8889}:80"
    volumes:
      - ../services/web_client/index.html:/usr/share/nginx/html/index.html:ro
      - ../services/web_client/style.css:/usr/share/nginx/html/style.css:ro
      - ../services/web_client/client.js:/usr/share/nginx/html/client.js:ro
      - ../services/web_client/nginx.conf:/etc/nginx/conf.d/default.conf:ro
    networks:
      - cortex_prime_network

networks:
  cortex_prime_network:
    driver: bridge
    name: ${PROJECT_NAME:-cortex-prime-mk1}_core_network

volumes:
  redis_data:
    name: ${PROJECT_NAME:-cortex-prime-mk1}_redis_core_data
