networks:
  cortex_prime_network:
    driver: bridge
    name: cortex_prime_network

services:
  api_gateway:
    build:
      context: ../services/api_gateway
      dockerfile: Dockerfile
    container_name: cortex-prime_api_gateway_mk1
    restart: unless-stopped
    ports:
      - "${GATEWAY_HOST_PORT:-8080}:8080"
    networks:
      - cortex_prime_network
    depends_on:
      - chimera_core
    volumes:
      - ../services/api_gateway:/app:rw
    env_file:
      - ../.env

  chimera_core:
    build:
      context: ../services/chimera_core
      dockerfile: Dockerfile
    container_name: cortex-prime_chimera_core_mk1
    restart: unless-stopped
    ports: # Exposing this is useful for direct debugging
      - "${CHIMERA_CORE_HOST_PORT:-8001}:8001"
    networks:
      - cortex_prime_network
    volumes:
      - ../services/chimera_core:/app:rw
      - ../agents:/app/agents:ro
    env_file:
      - ../.env

  voice_service:
    build:
      context: ../services/voice-service
      dockerfile: Dockerfile
    container_name: cortex-prime_voice_service_mk1
    restart: unless-stopped
    ports:
      - "8002:8002"
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]
    networks:
      - cortex_prime_network

  web_client:
    image: nginx:alpine
    container_name: cortex-prime_web_client_mk1
    restart: unless-stopped
    ports:
      - "81:81"
      - "443:443"
    volumes:
      - ../services/web_client/index.html:/usr/share/nginx/html/index.html:ro
      - ../services/web_client/style.css:/usr/share/nginx/html/style.css:ro
      - ../services/web_client/client.js:/usr/share/nginx/html/client.js:ro
      - ../services/web_client/nginx.ssl.conf:/etc/nginx/conf.d/default.conf:ro
      - ../infra/nginx/ssl:/etc/nginx/ssl:ro
    networks:
      - cortex_prime_network
