# ==============================================================================
#           MONUMENT MANIFEST (v1.0 - Sovereign Core Standard)
# ==============================================================================
# Standard Library: Simple Blog Platform Monument
# Infrastructure (Relics) + Intelligence (Agents) + Automation (Workflows)

kind: Monument
version: "1.0"
name: "blog_platform"
summary: "Standard autonomous blogging platform with AI content assistant"
author: "CORTEX_STD_LIB"
state: "stable"

description: |
  Standard blogging monument providing:
  - Content storage infrastructure
  - AI writing assistant
  - Automated content publishing workflow
  - Foundation for content management systems

# --- INFRASTRUCTURE STACK (Relics) ---
infrastructure:
  relics:
    - name: "content_store"
      type: "storage"
      path: "../../relics/kv_store/relic.yml"
      required: true
      config:
        purpose: "Blog post and metadata storage"

# --- INTELLIGENCE LAYER (Agents) ---
intelligence:
  agents:
    - name: "writing_assistant"
      role: "assistant"
      path: "../../agents/assistant/agent.yml"
      auto_start: true
      config:
        task: "Help users write and edit blog posts"

# --- AUTOMATION LAYER (Workflows) ---
automation:
  workflows:
    - name: "publish_pipeline"
      trigger: "on_demand"
      path: "../../workflows/data_pipeline/workflow.yml"
      config:
        description: "Process and publish blog content"

# --- DEPLOYMENT ---
deployment:
  type: "docker-compose"
  compose_file: "./docker-compose.yml"
  services:
    - content_store
  
  environment:
    BLOG_TITLE: "My AI-Powered Blog"
    BLOG_DESCRIPTION: "Autonomous blogging platform"

# --- MONUMENT INTERFACE ---
interface:
  type: "rest_api"
  base_url: "http://localhost:9001"
  endpoints:
    - name: "create_post"
      method: "POST"
      path: "/posts"
      description: "Create new blog post"
      
    - name: "get_posts"
      method: "GET"
      path: "/posts"
      description: "List all blog posts"
      
    - name: "get_post"
      method: "GET"
      path: "/posts/{id}"
      description: "Get specific blog post"

# --- CONFIGURATION ---
config:
  features:
    - "markdown_support"
    - "ai_writing_assistance"
    - "auto_tagging"
    - "scheduled_publishing"
  
  limits:
    max_posts: 1000
    max_post_size: "50KB"
    concurrent_users: 10

tags:
  - "std"
  - "monument"
  - "blog"
  - "content-management"
  - "ai-assisted"
  - "production"

metadata:
  complexity: "simple"
  components_count: 3
  estimated_resource_usage: "low"
  library: "std::manifests"
  version: "1.0.0"
