version: '3.8'

services:
  fact_store_app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: relic_fact_store
    restart: unless-stopped
    ports:
      - "${FACT_STORE_PORT:-8006}:8000"
    volumes:
      - fact_store_data:/data
    env_file:
      - .env.example

volumes:
  fact_store_data:
