# ==============================================================================
#           RELIC MANIFEST (v1.0 - Sovereign Core Standard)
# ==============================================================================

kind: Relic
version: "1.0"
name: "fact_store"
summary: "Simple persistent key-value storage for default-worker-agent"
author: "PRAETORIAN_CHIMERA"
state: "stable"

description: |
  A simple, persistent key-value storage service local to the
  default-worker-agent. Stores facts and metadata using SQLite.

service_type: "storage"

interface:
  type: "rest_api"
  base_url: "${FACT_STORE_URL:-http://localhost:8006}"
  
  endpoints:
    - name: "set_fact"
      method: "POST"
      path: "/set"
      parameters:
        key:
          type: "string"
          required: true
        value:
          type: "object"
          required: true
      description: "Store a fact"
    
    - name: "get_fact"
      method: "GET"
      path: "/get/{key}"
      parameters:
        key:
          type: "string"
          required: true
      description: "Retrieve a fact"
    
    - name: "delete_fact"
      method: "DELETE"
      path: "/delete/{key}"
      parameters:
        key:
          type: "string"
          required: true
      description: "Delete a fact"
    
    - name: "list_keys"
      method: "GET"
      path: "/keys"
      description: "List all fact keys"

health_check:
  type: "api_request"
  endpoint: "/health"
  method: "GET"
  expected_status: 200

deployment:
  type: "docker"
  docker_compose_file: "./docker-compose.yml"

persistence:
  type: "persistent_volume"
  size: "5Gi"

tags:
  - "storage"
  - "kv"
  - "worker-local"
  - "relic"
  - "production"
