# ==============================================================================
#           MONUMENT MANIFEST (v1.0 - Sovereign Core Standard)
# ==============================================================================
# Monument = Complete self-sustaining system
# Infrastructure (Relics) + Intelligence (Agents) + Automation (Workflows)

kind: Monument
version: "1.0"
name: "deep_search_engine"
summary: "Complete autonomous search engine with AI-powered synthesis"
author: "PRAETORIAN_CHIMERA"
state: "unstable"

description: |
  A fully autonomous search engine monument combining:
  - Multiple search providers (searxng, whoogle, duckduckgo)
  - Intelligent crawling and content extraction
  - Vector-based semantic search
  - LLM-powered answer synthesis
  - Automated maintenance and optimization

# --- INFRASTRUCTURE STACK (Relics) ---
infrastructure:
  relics:
    - name: "searxng"
      type: "search_provider"
      required: true
      
    - name: "vector_store"
      type: "storage"
      required: true
      
    - name: "postgres"
      type: "database"
      required: true
      
    - name: "redis"
      type: "cache"
      required: true
    
    - name: "llm_gateway"
      type: "processing"
      required: true

# --- INTELLIGENCE LAYER (Agents) ---
intelligence:
  agents:
    - name: "search_orchestrator"
      role: "orchestrator"
      auto_start: true
      
    - name: "web_crawler"
      role: "worker"
      instances: 3
      
    - name: "content_indexer"
      role: "worker"
      instances: 2
      
    - name: "query_processor"
      role: "worker"
      instances: 5
      
    - name: "answer_synthesizer"
      role: "worker"
      instances: 3

# --- AUTOMATION LAYER (Workflows) ---
automation:
  workflows:
    - name: "search_pipeline"
      trigger: "on_query"
      
    - name: "crawl_and_index"
      trigger: "scheduled"
      schedule: "*/30 * * * *"
      
    - name: "optimize_indexes"
      trigger: "scheduled"
      schedule: "0 2 * * *"

# --- DEPLOYMENT ---
deployment:
  type: "docker-compose"
  compose_file: "./docker-compose.yml"

# --- MONUMENT INTERFACE ---
interface:
  type: "rest_api"
  base_url: "http://monument-search:8000"
  endpoints:
    - name: "search"
      method: "POST"
      path: "/search"

tags:
  - "monument"
  - "search-engine"
  - "autonomous"
